### ISSUE TITLE
Issue starting vagrant box

### ISSUE THREAD

**Issue by granthbr** [jbetanzos/puppet-centos-mule-apiumbrella#1]
@jbetanzos 
I'm getting the following error when I attempt to bring the box up. 

_There are errors in the configuration of this machine. Please fix
the following errors and try again:_

_vm:_
_\* The host path of the shared folder is missing: mule/apps_

_puppet provisioner:_
_\* The configured module path doesn't exist: /Users/BGRANTHAM/project/puppet-centos-mule-apiumbrella/puppet/modules_

**Comment by jbetanzos** [comment]
The missing directory has been added, you can pull the project again

**Comment by granthbr** [comment]
Still missing the modules dir:

There are errors in the configuration of this machine. Please fix
the following errors and try again:

puppet provisioner:
- The configured module path doesn't exist: /Users/BGRANTHAM/project/puppet-centos-mule-apiumbrella/puppet/modules
