### ISSUE TITLE
still an issue

### ISSUE THREAD

**Issue by granthbr** [jbetanzos/puppet-centos-mule-apiumbrella#2]
Still missing the modules 

Still missing the modules dir:

There are errors in the configuration of this machine. Please fix
the following errors and try again:

puppet provisioner:

The configured module path doesn't exist: /Users/BGRANTHAM/project/puppet-centos-mule-apiumbrella/puppet/modules

**Comment by jbetanzos** [comment]
Errors are fix, please check and try again
